# frozen_string_literal: true

class Chart
  attr_accessor :grid, :inputs, :state, :outputs

  # https://datahub.io/core/global-temp
  def tick
    defaults
    render
  end

  def defaults
    state.chart_grid.width = 1000
    state.chart_grid.height = 620
    state.chart_grid.x = grid.w_half - (state.chart_grid.width / 2)
    state.chart_grid.y = 60

    defaults_data
    state.dataset_used = state.dataset.select { |d| d[:Source] == 'GISTEMP' }.reverse
    state.dataset_max_y = state.dataset_used.max_by { |d| d[:Mean] }[:Mean].to_f
    state.dataset_min_y = state.dataset_used.min_by { |d| d[:Mean] }[:Mean].to_f
    state.dataset_max_x = state.dataset_used.max_by { |d| d[:Year] }[:Year].to_f
    state.dataset_min_x = state.dataset_used.min_by { |d| d[:Year] }[:Year].to_f
  end

  def render
    # Titles
    outputs.labels << [640, grid.h - 20,
                       'Annual mean temperature anomalies in degrees Celsius relative to a base period', 0, 1]
    outputs.labels << [640, 40, 'Year', 0, 1]
    outputs.labels << [state.chart_grid.x - 40, grid.h_half - 0, 'Mean', 0, 1]
    outputs.labels << [grid.right - 360, grid.bottom + 20, 'Source: https://datahub.io/core/global-temp', -2, 0]

    # Chart box
    outputs.borders << [state.chart_grid.x, state.chart_grid.y, state.chart_grid.width, state.chart_grid.height,
                        128, 128, 128]

    # Y axis gridlines
    outputs.lines << [calc_scaled_x(1880), calc_scaled_y(0.5), calc_scaled_x(2016), calc_scaled_y(0.5), 211, 211,
                      211]
    outputs.lines << [calc_scaled_x(1880), calc_scaled_y(0), calc_scaled_x(2016), calc_scaled_y(0), 255]

    # X axis gridlines
    outputs.lines << [calc_scaled_x(1900), calc_scaled_y(state.dataset_min_y), calc_scaled_x(1900),
                      calc_scaled_y(state.dataset_max_y), 211, 211, 211]
    outputs.lines << [calc_scaled_x(1920), calc_scaled_y(state.dataset_min_y), calc_scaled_x(1920),
                      calc_scaled_y(state.dataset_max_y), 211, 211, 211]
    outputs.lines << [calc_scaled_x(1940), calc_scaled_y(state.dataset_min_y), calc_scaled_x(1940),
                      calc_scaled_y(state.dataset_max_y), 211, 211, 211]
    outputs.lines << [calc_scaled_x(1960), calc_scaled_y(state.dataset_min_y), calc_scaled_x(1960),
                      calc_scaled_y(state.dataset_max_y), 211, 211, 211]
    outputs.lines << [calc_scaled_x(1980), calc_scaled_y(state.dataset_min_y), calc_scaled_x(1980),
                      calc_scaled_y(state.dataset_max_y), 211, 211, 211]
    outputs.lines << [calc_scaled_x(2000), calc_scaled_y(state.dataset_min_y), calc_scaled_x(2000),
                      calc_scaled_y(state.dataset_max_y), 211, 211, 211]

    # Y axis labels
    outputs.labels << [state.chart_grid.x, calc_scaled_y(state.dataset_max_y) + 7, state.dataset_max_y.to_s, -3, 2]
    outputs.labels << [state.chart_grid.x, calc_scaled_y(0.5) + 7, '0.5', -3, 2]
    outputs.labels << [state.chart_grid.x, calc_scaled_y(0.0) + 7, '0', -3, 2]
    outputs.labels << [state.chart_grid.x, calc_scaled_y(state.dataset_min_y) + 7, state.dataset_min_y.to_s, -3, 2]

    # X axis labels
    outputs.labels << [calc_scaled_x(1880), state.chart_grid.y - 10, '1880', -3, 1]
    outputs.labels << [calc_scaled_x(1900), state.chart_grid.y - 10, '1900', -3, 1]
    outputs.labels << [calc_scaled_x(1920), state.chart_grid.y - 10, '1920', -3, 1]
    outputs.labels << [calc_scaled_x(1940), state.chart_grid.y - 10, '1940', -3, 1]
    outputs.labels << [calc_scaled_x(1960), state.chart_grid.y - 10, '1960', -3, 1]
    outputs.labels << [calc_scaled_x(1980), state.chart_grid.y - 10, '1980', -3, 1]
    outputs.labels << [calc_scaled_x(2000), state.chart_grid.y - 10, '2000', -3, 1]
    outputs.labels << [calc_scaled_x(2016), state.chart_grid.y - 10, '2016', -3, 1]

    # Plot the data
    state.dataset_used.each_with_index do |d, idx|
      break if (idx + 1) >= state.dataset_used.length

      y = calc_scaled_y(d[:Mean])
      x = calc_scaled_x(d[:Year])

      next_data = state.dataset_used[idx + 1]

      next_data_y = calc_scaled_y(next_data[:Mean])
      next_data_x = calc_scaled_x(next_data[:Year])

      outputs.lines << [x, y, next_data_x, next_data_y]
    end
  end

  def calc_scaled_y(data_value)
    height = state.chart_grid.height + state.chart_grid.y
    val = state.chart_grid.y + (data_value - state.dataset_min_y) * (height - state.chart_grid.y) / (state.dataset_max_y - state.dataset_min_y)
  end

  def calc_scaled_x(data_value)
    width = state.chart_grid.width + state.chart_grid.x
    state.chart_grid.x + (data_value - state.dataset_min_x) * (width - state.chart_grid.x) / (state.dataset_max_x - state.dataset_min_x)
  end

  def defaults_data
    state.dataset = [{
      "Mean": 0.9363,
      "Source": 'GCAG',
      "Year": 2016
    }, {
      "Mean": 0.99,
      "Source": 'GISTEMP',
      "Year": 2016
    }, {
      "Mean": 0.8998,
      "Source": 'GCAG',
      "Year": 2015
    }, {
      "Mean": 0.87,
      "Source": 'GISTEMP',
      "Year": 2015
    }, {
      "Mean": 0.7408,
      "Source": 'GCAG',
      "Year": 2014
    }, {
      "Mean": 0.74,
      "Source": 'GISTEMP',
      "Year": 2014
    }, {
      "Mean": 0.6679,
      "Source": 'GCAG',
      "Year": 2013
    }, {
      "Mean": 0.65,
      "Source": 'GISTEMP',
      "Year": 2013
    }, {
      "Mean": 0.624,
      "Source": 'GCAG',
      "Year": 2012
    }, {
      "Mean": 0.63,
      "Source": 'GISTEMP',
      "Year": 2012
    }, {
      "Mean": 0.5788,
      "Source": 'GCAG',
      "Year": 2011
    }, {
      "Mean": 0.6,
      "Source": 'GISTEMP',
      "Year": 2011
    }, {
      "Mean": 0.7014,
      "Source": 'GCAG',
      "Year": 2010
    }, {
      "Mean": 0.71,
      "Source": 'GISTEMP',
      "Year": 2010
    }, {
      "Mean": 0.6367,
      "Source": 'GCAG',
      "Year": 2009
    }, {
      "Mean": 0.64,
      "Source": 'GISTEMP',
      "Year": 2009
    }, {
      "Mean": 0.5419,
      "Source": 'GCAG',
      "Year": 2008
    }, {
      "Mean": 0.54,
      "Source": 'GISTEMP',
      "Year": 2008
    }, {
      "Mean": 0.61,
      "Source": 'GCAG',
      "Year": 2007
    }, {
      "Mean": 0.66,
      "Source": 'GISTEMP',
      "Year": 2007
    }, {
      "Mean": 0.6125,
      "Source": 'GCAG',
      "Year": 2006
    }, {
      "Mean": 0.63,
      "Source": 'GISTEMP',
      "Year": 2006
    }, {
      "Mean": 0.6585,
      "Source": 'GCAG',
      "Year": 2005
    }, {
      "Mean": 0.69,
      "Source": 'GISTEMP',
      "Year": 2005
    }, {
      "Mean": 0.5783,
      "Source": 'GCAG',
      "Year": 2004
    }, {
      "Mean": 0.55,
      "Source": 'GISTEMP',
      "Year": 2004
    }, {
      "Mean": 0.6134,
      "Source": 'GCAG',
      "Year": 2003
    }, {
      "Mean": 0.62,
      "Source": 'GISTEMP',
      "Year": 2003
    }, {
      "Mean": 0.6023,
      "Source": 'GCAG',
      "Year": 2002
    }, {
      "Mean": 0.63,
      "Source": 'GISTEMP',
      "Year": 2002
    }, {
      "Mean": 0.5473,
      "Source": 'GCAG',
      "Year": 2001
    }, {
      "Mean": 0.55,
      "Source": 'GISTEMP',
      "Year": 2001
    }, {
      "Mean": 0.4262,
      "Source": 'GCAG',
      "Year": 2000
    }, {
      "Mean": 0.42,
      "Source": 'GISTEMP',
      "Year": 2000
    }, {
      "Mean": 0.4438,
      "Source": 'GCAG',
      "Year": 1999
    }, {
      "Mean": 0.42,
      "Source": 'GISTEMP',
      "Year": 1999
    }, {
      "Mean": 0.6344,
      "Source": 'GCAG',
      "Year": 1998
    }, {
      "Mean": 0.64,
      "Source": 'GISTEMP',
      "Year": 1998
    }, {
      "Mean": 0.5187,
      "Source": 'GCAG',
      "Year": 1997
    }, {
      "Mean": 0.48,
      "Source": 'GISTEMP',
      "Year": 1997
    }, {
      "Mean": 0.3228,
      "Source": 'GCAG',
      "Year": 1996
    }, {
      "Mean": 0.35,
      "Source": 'GISTEMP',
      "Year": 1996
    }, {
      "Mean": 0.4577,
      "Source": 'GCAG',
      "Year": 1995
    }, {
      "Mean": 0.46,
      "Source": 'GISTEMP',
      "Year": 1995
    }, {
      "Mean": 0.3409,
      "Source": 'GCAG',
      "Year": 1994
    }, {
      "Mean": 0.32,
      "Source": 'GISTEMP',
      "Year": 1994
    }, {
      "Mean": 0.2853,
      "Source": 'GCAG',
      "Year": 1993
    }, {
      "Mean": 0.24,
      "Source": 'GISTEMP',
      "Year": 1993
    }, {
      "Mean": 0.2571,
      "Source": 'GCAG',
      "Year": 1992
    }, {
      "Mean": 0.23,
      "Source": 'GISTEMP',
      "Year": 1992
    }, {
      "Mean": 0.4055,
      "Source": 'GCAG',
      "Year": 1991
    }, {
      "Mean": 0.43,
      "Source": 'GISTEMP',
      "Year": 1991
    }, {
      "Mean": 0.4328,
      "Source": 'GCAG',
      "Year": 1990
    }, {
      "Mean": 0.44,
      "Source": 'GISTEMP',
      "Year": 1990
    }, {
      "Mean": 0.297,
      "Source": 'GCAG',
      "Year": 1989
    }, {
      "Mean": 0.29,
      "Source": 'GISTEMP',
      "Year": 1989
    }, {
      "Mean": 0.3757,
      "Source": 'GCAG',
      "Year": 1988
    }, {
      "Mean": 0.41,
      "Source": 'GISTEMP',
      "Year": 1988
    }, {
      "Mean": 0.3696,
      "Source": 'GCAG',
      "Year": 1987
    }, {
      "Mean": 0.33,
      "Source": 'GISTEMP',
      "Year": 1987
    }, {
      "Mean": 0.2296,
      "Source": 'GCAG',
      "Year": 1986
    }, {
      "Mean": 0.19,
      "Source": 'GISTEMP',
      "Year": 1986
    }, {
      "Mean": 0.1342,
      "Source": 'GCAG',
      "Year": 1985
    }, {
      "Mean": 0.12,
      "Source": 'GISTEMP',
      "Year": 1985
    }, {
      "Mean": 0.149,
      "Source": 'GCAG',
      "Year": 1984
    }, {
      "Mean": 0.15,
      "Source": 'GISTEMP',
      "Year": 1984
    }, {
      "Mean": 0.3411,
      "Source": 'GCAG',
      "Year": 1983
    }, {
      "Mean": 0.3,
      "Source": 'GISTEMP',
      "Year": 1983
    }, {
      "Mean": 0.1815,
      "Source": 'GCAG',
      "Year": 1982
    }, {
      "Mean": 0.13,
      "Source": 'GISTEMP',
      "Year": 1982
    }, {
      "Mean": 0.2999,
      "Source": 'GCAG',
      "Year": 1981
    }, {
      "Mean": 0.33,
      "Source": 'GISTEMP',
      "Year": 1981
    }, {
      "Mean": 0.2637,
      "Source": 'GCAG',
      "Year": 1980
    }, {
      "Mean": 0.27,
      "Source": 'GISTEMP',
      "Year": 1980
    }, {
      "Mean": 0.2273,
      "Source": 'GCAG',
      "Year": 1979
    }, {
      "Mean": 0.17,
      "Source": 'GISTEMP',
      "Year": 1979
    }, {
      "Mean": 0.1123,
      "Source": 'GCAG',
      "Year": 1978
    }, {
      "Mean": 0.07,
      "Source": 'GISTEMP',
      "Year": 1978
    }, {
      "Mean": 0.1978,
      "Source": 'GCAG',
      "Year": 1977
    }, {
      "Mean": 0.18,
      "Source": 'GISTEMP',
      "Year": 1977
    }, {
      "Mean": -0.0792,
      "Source": 'GCAG',
      "Year": 1976
    }, {
      "Mean": -0.11,
      "Source": 'GISTEMP',
      "Year": 1976
    }, {
      "Mean": 0.0034,
      "Source": 'GCAG',
      "Year": 1975
    }, {
      "Mean": -0.02,
      "Source": 'GISTEMP',
      "Year": 1975
    }, {
      "Mean": -0.0719,
      "Source": 'GCAG',
      "Year": 1974
    }, {
      "Mean": -0.07,
      "Source": 'GISTEMP',
      "Year": 1974
    }, {
      "Mean": 0.1641,
      "Source": 'GCAG',
      "Year": 1973
    }, {
      "Mean": 0.15,
      "Source": 'GISTEMP',
      "Year": 1973
    }, {
      "Mean": 0.0264,
      "Source": 'GCAG',
      "Year": 1972
    }, {
      "Mean": 0.01,
      "Source": 'GISTEMP',
      "Year": 1972
    }, {
      "Mean": -0.0783,
      "Source": 'GCAG',
      "Year": 1971
    }, {
      "Mean": -0.09,
      "Source": 'GISTEMP',
      "Year": 1971
    }, {
      "Mean": 0.0372,
      "Source": 'GCAG',
      "Year": 1970
    }, {
      "Mean": 0.02,
      "Source": 'GISTEMP',
      "Year": 1970
    }, {
      "Mean": 0.0929,
      "Source": 'GCAG',
      "Year": 1969
    }, {
      "Mean": 0.07,
      "Source": 'GISTEMP',
      "Year": 1969
    }, {
      "Mean": -0.0296,
      "Source": 'GCAG',
      "Year": 1968
    }, {
      "Mean": -0.07,
      "Source": 'GISTEMP',
      "Year": 1968
    }, {
      "Mean": -0.0131,
      "Source": 'GCAG',
      "Year": 1967
    }, {
      "Mean": -0.02,
      "Source": 'GISTEMP',
      "Year": 1967
    }, {
      "Mean": -0.0227,
      "Source": 'GCAG',
      "Year": 1966
    }, {
      "Mean": -0.05,
      "Source": 'GISTEMP',
      "Year": 1966
    }, {
      "Mean": -0.078,
      "Source": 'GCAG',
      "Year": 1965
    }, {
      "Mean": -0.1,
      "Source": 'GISTEMP',
      "Year": 1965
    }, {
      "Mean": -0.1495,
      "Source": 'GCAG',
      "Year": 1964
    }, {
      "Mean": -0.2,
      "Source": 'GISTEMP',
      "Year": 1964
    }, {
      "Mean": 0.1068,
      "Source": 'GCAG',
      "Year": 1963
    }, {
      "Mean": 0.06,
      "Source": 'GISTEMP',
      "Year": 1963
    }, {
      "Mean": 0.0888,
      "Source": 'GCAG',
      "Year": 1962
    }, {
      "Mean": 0.03,
      "Source": 'GISTEMP',
      "Year": 1962
    }, {
      "Mean": 0.0775,
      "Source": 'GCAG',
      "Year": 1961
    }, {
      "Mean": 0.05,
      "Source": 'GISTEMP',
      "Year": 1961
    }, {
      "Mean": 0.0204,
      "Source": 'GCAG',
      "Year": 1960
    }, {
      "Mean": -0.02,
      "Source": 'GISTEMP',
      "Year": 1960
    }, {
      "Mean": 0.0596,
      "Source": 'GCAG',
      "Year": 1959
    }, {
      "Mean": 0.03,
      "Source": 'GISTEMP',
      "Year": 1959
    }, {
      "Mean": 0.1095,
      "Source": 'GCAG',
      "Year": 1958
    }, {
      "Mean": 0.07,
      "Source": 'GISTEMP',
      "Year": 1958
    }, {
      "Mean": 0.0488,
      "Source": 'GCAG',
      "Year": 1957
    }, {
      "Mean": 0.04,
      "Source": 'GISTEMP',
      "Year": 1957
    }, {
      "Mean": -0.199,
      "Source": 'GCAG',
      "Year": 1956
    }, {
      "Mean": -0.2,
      "Source": 'GISTEMP',
      "Year": 1956
    }, {
      "Mean": -0.1354,
      "Source": 'GCAG',
      "Year": 1955
    }, {
      "Mean": -0.15,
      "Source": 'GISTEMP',
      "Year": 1955
    }, {
      "Mean": -0.1165,
      "Source": 'GCAG',
      "Year": 1954
    }, {
      "Mean": -0.13,
      "Source": 'GISTEMP',
      "Year": 1954
    }, {
      "Mean": 0.0952,
      "Source": 'GCAG',
      "Year": 1953
    }, {
      "Mean": 0.08,
      "Source": 'GISTEMP',
      "Year": 1953
    }, {
      "Mean": 0.0248,
      "Source": 'GCAG',
      "Year": 1952
    }, {
      "Mean": 0.01,
      "Source": 'GISTEMP',
      "Year": 1952
    }, {
      "Mean": -0.0132,
      "Source": 'GCAG',
      "Year": 1951
    }, {
      "Mean": -0.07,
      "Source": 'GISTEMP',
      "Year": 1951
    }, {
      "Mean": -0.1616,
      "Source": 'GCAG',
      "Year": 1950
    }, {
      "Mean": -0.18,
      "Source": 'GISTEMP',
      "Year": 1950
    }, {
      "Mean": -0.0568,
      "Source": 'GCAG',
      "Year": 1949
    }, {
      "Mean": -0.09,
      "Source": 'GISTEMP',
      "Year": 1949
    }, {
      "Mean": -0.0487,
      "Source": 'GCAG',
      "Year": 1948
    }, {
      "Mean": -0.09,
      "Source": 'GISTEMP',
      "Year": 1948
    }, {
      "Mean": -0.0477,
      "Source": 'GCAG',
      "Year": 1947
    }, {
      "Mean": -0.05,
      "Source": 'GISTEMP',
      "Year": 1947
    }, {
      "Mean": -0.004,
      "Source": 'GCAG',
      "Year": 1946
    }, {
      "Mean": -0.04,
      "Source": 'GISTEMP',
      "Year": 1946
    }, {
      "Mean": 0.171,
      "Source": 'GCAG',
      "Year": 1945
    }, {
      "Mean": 0.12,
      "Source": 'GISTEMP',
      "Year": 1945
    }, {
      "Mean": 0.2928,
      "Source": 'GCAG',
      "Year": 1944
    }, {
      "Mean": 0.25,
      "Source": 'GISTEMP',
      "Year": 1944
    }, {
      "Mean": 0.157,
      "Source": 'GCAG',
      "Year": 1943
    }, {
      "Mean": 0.13,
      "Source": 'GISTEMP',
      "Year": 1943
    }, {
      "Mean": 0.1538,
      "Source": 'GCAG',
      "Year": 1942
    }, {
      "Mean": 0.09,
      "Source": 'GISTEMP',
      "Year": 1942
    }, {
      "Mean": 0.196,
      "Source": 'GCAG',
      "Year": 1941
    }, {
      "Mean": 0.12,
      "Source": 'GISTEMP',
      "Year": 1941
    }, {
      "Mean": 0.0947,
      "Source": 'GCAG',
      "Year": 1940
    }, {
      "Mean": 0.08,
      "Source": 'GISTEMP',
      "Year": 1940
    }, {
      "Mean": -0.0139,
      "Source": 'GCAG',
      "Year": 1939
    }, {
      "Mean": -0.03,
      "Source": 'GISTEMP',
      "Year": 1939
    }, {
      "Mean": -0.0288,
      "Source": 'GCAG',
      "Year": 1938
    }, {
      "Mean": -0.03,
      "Source": 'GISTEMP',
      "Year": 1938
    }, {
      "Mean": -0.0157,
      "Source": 'GCAG',
      "Year": 1937
    }, {
      "Mean": -0.03,
      "Source": 'GISTEMP',
      "Year": 1937
    }, {
      "Mean": -0.1134,
      "Source": 'GCAG',
      "Year": 1936
    }, {
      "Mean": -0.15,
      "Source": 'GISTEMP',
      "Year": 1936
    }, {
      "Mean": -0.1392,
      "Source": 'GCAG',
      "Year": 1935
    }, {
      "Mean": -0.2,
      "Source": 'GISTEMP',
      "Year": 1935
    }, {
      "Mean": -0.1015,
      "Source": 'GCAG',
      "Year": 1934
    }, {
      "Mean": -0.14,
      "Source": 'GISTEMP',
      "Year": 1934
    }, {
      "Mean": -0.2439,
      "Source": 'GCAG',
      "Year": 1933
    }, {
      "Mean": -0.29,
      "Source": 'GISTEMP',
      "Year": 1933
    }, {
      "Mean": -0.1168,
      "Source": 'GCAG',
      "Year": 1932
    }, {
      "Mean": -0.17,
      "Source": 'GISTEMP',
      "Year": 1932
    }, {
      "Mean": -0.0686,
      "Source": 'GCAG',
      "Year": 1931
    }, {
      "Mean": -0.09,
      "Source": 'GISTEMP',
      "Year": 1931
    }, {
      "Mean": -0.1003,
      "Source": 'GCAG',
      "Year": 1930
    }, {
      "Mean": -0.15,
      "Source": 'GISTEMP',
      "Year": 1930
    }, {
      "Mean": -0.2985,
      "Source": 'GCAG',
      "Year": 1929
    }, {
      "Mean": -0.36,
      "Source": 'GISTEMP',
      "Year": 1929
    }, {
      "Mean": -0.1774,
      "Source": 'GCAG',
      "Year": 1928
    }, {
      "Mean": -0.21,
      "Source": 'GISTEMP',
      "Year": 1928
    }, {
      "Mean": -0.1546,
      "Source": 'GCAG',
      "Year": 1927
    }, {
      "Mean": -0.21,
      "Source": 'GISTEMP',
      "Year": 1927
    }, {
      "Mean": -0.0667,
      "Source": 'GCAG',
      "Year": 1926
    }, {
      "Mean": -0.1,
      "Source": 'GISTEMP',
      "Year": 1926
    }, {
      "Mean": -0.1481,
      "Source": 'GCAG',
      "Year": 1925
    }, {
      "Mean": -0.21,
      "Source": 'GISTEMP',
      "Year": 1925
    }, {
      "Mean": -0.2486,
      "Source": 'GCAG',
      "Year": 1924
    }, {
      "Mean": -0.28,
      "Source": 'GISTEMP',
      "Year": 1924
    }, {
      "Mean": -0.2156,
      "Source": 'GCAG',
      "Year": 1923
    }, {
      "Mean": -0.24,
      "Source": 'GISTEMP',
      "Year": 1923
    }, {
      "Mean": -0.2304,
      "Source": 'GCAG',
      "Year": 1922
    }, {
      "Mean": -0.28,
      "Source": 'GISTEMP',
      "Year": 1922
    }, {
      "Mean": -0.1485,
      "Source": 'GCAG',
      "Year": 1921
    }, {
      "Mean": -0.21,
      "Source": 'GISTEMP',
      "Year": 1921
    }, {
      "Mean": -0.2105,
      "Source": 'GCAG',
      "Year": 1920
    }, {
      "Mean": -0.27,
      "Source": 'GISTEMP',
      "Year": 1920
    }, {
      "Mean": -0.2055,
      "Source": 'GCAG',
      "Year": 1919
    }, {
      "Mean": -0.22,
      "Source": 'GISTEMP',
      "Year": 1919
    }, {
      "Mean": -0.2084,
      "Source": 'GCAG',
      "Year": 1918
    }, {
      "Mean": -0.26,
      "Source": 'GISTEMP',
      "Year": 1918
    }, {
      "Mean": -0.3146,
      "Source": 'GCAG',
      "Year": 1917
    }, {
      "Mean": -0.4,
      "Source": 'GISTEMP',
      "Year": 1917
    }, {
      "Mean": -0.293,
      "Source": 'GCAG',
      "Year": 1916
    }, {
      "Mean": -0.34,
      "Source": 'GISTEMP',
      "Year": 1916
    }, {
      "Mean": -0.0693,
      "Source": 'GCAG',
      "Year": 1915
    }, {
      "Mean": -0.11,
      "Source": 'GISTEMP',
      "Year": 1915
    }, {
      "Mean": -0.1395,
      "Source": 'GCAG',
      "Year": 1914
    }, {
      "Mean": -0.16,
      "Source": 'GISTEMP',
      "Year": 1914
    }, {
      "Mean": -0.3162,
      "Source": 'GCAG',
      "Year": 1913
    }, {
      "Mean": -0.34,
      "Source": 'GISTEMP',
      "Year": 1913
    }, {
      "Mean": -0.3288,
      "Source": 'GCAG',
      "Year": 1912
    }, {
      "Mean": -0.35,
      "Source": 'GISTEMP',
      "Year": 1912
    }, {
      "Mean": -0.4332,
      "Source": 'GCAG',
      "Year": 1911
    }, {
      "Mean": -0.44,
      "Source": 'GISTEMP',
      "Year": 1911
    }, {
      "Mean": -0.3789,
      "Source": 'GCAG',
      "Year": 1910
    }, {
      "Mean": -0.42,
      "Source": 'GISTEMP',
      "Year": 1910
    }, {
      "Mean": -0.4261,
      "Source": 'GCAG',
      "Year": 1909
    }, {
      "Mean": -0.47,
      "Source": 'GISTEMP',
      "Year": 1909
    }, {
      "Mean": -0.4396,
      "Source": 'GCAG',
      "Year": 1908
    }, {
      "Mean": -0.43,
      "Source": 'GISTEMP',
      "Year": 1908
    }, {
      "Mean": -0.3706,
      "Source": 'GCAG',
      "Year": 1907
    }, {
      "Mean": -0.4,
      "Source": 'GISTEMP',
      "Year": 1907
    }, {
      "Mean": -0.2174,
      "Source": 'GCAG',
      "Year": 1906
    }, {
      "Mean": -0.23,
      "Source": 'GISTEMP',
      "Year": 1906
    }, {
      "Mean": -0.2931,
      "Source": 'GCAG',
      "Year": 1905
    }, {
      "Mean": -0.28,
      "Source": 'GISTEMP',
      "Year": 1905
    }, {
      "Mean": -0.4194,
      "Source": 'GCAG',
      "Year": 1904
    }, {
      "Mean": -0.44,
      "Source": 'GISTEMP',
      "Year": 1904
    }, {
      "Mean": -0.3369,
      "Source": 'GCAG',
      "Year": 1903
    }, {
      "Mean": -0.35,
      "Source": 'GISTEMP',
      "Year": 1903
    }, {
      "Mean": -0.2463,
      "Source": 'GCAG',
      "Year": 1902
    }, {
      "Mean": -0.27,
      "Source": 'GISTEMP',
      "Year": 1902
    }, {
      "Mean": -0.1417,
      "Source": 'GCAG',
      "Year": 1901
    }, {
      "Mean": -0.15,
      "Source": 'GISTEMP',
      "Year": 1901
    }, {
      "Mean": -0.0679,
      "Source": 'GCAG',
      "Year": 1900
    }, {
      "Mean": -0.09,
      "Source": 'GISTEMP',
      "Year": 1900
    }, {
      "Mean": -0.1173,
      "Source": 'GCAG',
      "Year": 1899
    }, {
      "Mean": -0.16,
      "Source": 'GISTEMP',
      "Year": 1899
    }, {
      "Mean": -0.2546,
      "Source": 'GCAG',
      "Year": 1898
    }, {
      "Mean": -0.28,
      "Source": 'GISTEMP',
      "Year": 1898
    }, {
      "Mean": -0.1224,
      "Source": 'GCAG',
      "Year": 1897
    }, {
      "Mean": -0.11,
      "Source": 'GISTEMP',
      "Year": 1897
    }, {
      "Mean": -0.0974,
      "Source": 'GCAG',
      "Year": 1896
    }, {
      "Mean": -0.15,
      "Source": 'GISTEMP',
      "Year": 1896
    }, {
      "Mean": -0.229,
      "Source": 'GCAG',
      "Year": 1895
    }, {
      "Mean": -0.21,
      "Source": 'GISTEMP',
      "Year": 1895
    }, {
      "Mean": -0.2808,
      "Source": 'GCAG',
      "Year": 1894
    }, {
      "Mean": -0.31,
      "Source": 'GISTEMP',
      "Year": 1894
    }, {
      "Mean": -0.3212,
      "Source": 'GCAG',
      "Year": 1893
    }, {
      "Mean": -0.3,
      "Source": 'GISTEMP',
      "Year": 1893
    }, {
      "Mean": -0.3062,
      "Source": 'GCAG',
      "Year": 1892
    }, {
      "Mean": -0.27,
      "Source": 'GISTEMP',
      "Year": 1892
    }, {
      "Mean": -0.2532,
      "Source": 'GCAG',
      "Year": 1891
    }, {
      "Mean": -0.24,
      "Source": 'GISTEMP',
      "Year": 1891
    }, {
      "Mean": -0.322,
      "Source": 'GCAG',
      "Year": 1890
    }, {
      "Mean": -0.37,
      "Source": 'GISTEMP',
      "Year": 1890
    }, {
      "Mean": -0.0982,
      "Source": 'GCAG',
      "Year": 1889
    }, {
      "Mean": -0.12,
      "Source": 'GISTEMP',
      "Year": 1889
    }, {
      "Mean": -0.1471,
      "Source": 'GCAG',
      "Year": 1888
    }, {
      "Mean": -0.2,
      "Source": 'GISTEMP',
      "Year": 1888
    }, {
      "Mean": -0.2489,
      "Source": 'GCAG',
      "Year": 1887
    }, {
      "Mean": -0.33,
      "Source": 'GISTEMP',
      "Year": 1887
    }, {
      "Mean": -0.2003,
      "Source": 'GCAG',
      "Year": 1886
    }, {
      "Mean": -0.31,
      "Source": 'GISTEMP',
      "Year": 1886
    }, {
      "Mean": -0.2125,
      "Source": 'GCAG',
      "Year": 1885
    }, {
      "Mean": -0.32,
      "Source": 'GISTEMP',
      "Year": 1885
    }, {
      "Mean": -0.2009,
      "Source": 'GCAG',
      "Year": 1884
    }, {
      "Mean": -0.28,
      "Source": 'GISTEMP',
      "Year": 1884
    }, {
      "Mean": -0.1424,
      "Source": 'GCAG',
      "Year": 1883
    }, {
      "Mean": -0.21,
      "Source": 'GISTEMP',
      "Year": 1883
    }, {
      "Mean": -0.0648,
      "Source": 'GCAG',
      "Year": 1882
    }, {
      "Mean": -0.1,
      "Source": 'GISTEMP',
      "Year": 1882
    }, {
      "Mean": -0.0628,
      "Source": 'GCAG',
      "Year": 1881
    }, {
      "Mean": -0.12,
      "Source": 'GISTEMP',
      "Year": 1881
    }, {
      "Mean": -0.1148,
      "Source": 'GCAG',
      "Year": 1880
    }, {
      "Mean": -0.2,
      "Source": 'GISTEMP',
      "Year": 1880
    }]
  end
end

$chart = Chart.new

def tick(args)
  $chart.inputs = args.inputs
  $chart.state = args.state
  $chart.outputs = args.outputs
  $chart.grid    = args.grid
  $chart.tick
end
